### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [PrivateCoffee/matrix-gptbot#10]
can i put in a room name under allowedusers in the config to allow anyone in the room to use the bot?

If not that would be a great addition

**Comment by dillfrescott** [comment]
like

`!pAuoOPLJSiyvaLVeUV:matrix.org` just as an example

**Comment by kumitterer** [comment]
Hi, thanks for your suggestion – this is now possible in the new `v0.3.10`.

https://github.com/PrivateCoffee/matrix-gptbot/blob/15a93d823134098fc077b68ead0cfaefa995edfa/config.dist.ini#L52
https://github.com/PrivateCoffee/matrix-gptbot/blob/15a93d823134098fc077b68ead0cfaefa995edfa/src/gptbot/classes/bot.py#L592-L604

CI is currently building a new release for Docker Hub and PyPI, so you should be able to update to the new version shortly.

**Comment by dillfrescott** [comment]
Thank you so much!!!
