### ISSUE TITLE
Bot completely broken after machine reboot

### ISSUE THREAD

**Issue by dillfrescott** [PrivateCoffee/matrix-gptbot#12]
```
May 17 02:53:09 matrix systemd[752]: Started Matrix GPT Bot.
May 17 02:53:13 matrix bot.sh[952]: Error validating response: 'next_batch' is a required property
May 17 02:53:13 matrix bot.sh[952]: [2024-05-17 02:53:13:585322] - run - [INFO] Running migrations...
May 17 02:53:13 matrix bot.sh[952]: [2024-05-17 02:53:13:589641] - run - [INFO] Already at latest version 8.
May 17 02:53:13 matrix bot.sh[952]: [2024-05-17 02:53:13:614485] - run - [CRITICAL] Initial sync failed, aborting: SyncError: M_UNKNOWN_TOKEN Unrecognised access token.
May 17 02:53:13 matrix bot.sh[952]: Received SIGTERM - exiting...
May 17 02:53:13 matrix systemd[752]: aiko.service: Consumed 1.843s CPU time.
```

It will not start

**Comment by dillfrescott** [comment]
Hmm after further debugging the issue seems to lie with pantalaimon again.

I really hate that software, for good reason.

It doesn't work well at all

The documentation is vague and sparse

It doesnt seem to be your bots fault. it all lies with panta.

ill close this as it is out of your control!

**Comment by kumitterer** [comment]
I have an idea as to what the issue might be there. In the default configuration, Pantalaimon tries to use the system key ring to store keys, but that seems somewhat unreliable, and probably won't work at all if you're using Docker.

I have amended the provided config file: https://github.com/PrivateCoffee/matrix-gptbot/blob/5bbcd3cfdad7b303cd8bce713cf785f4dcbb1dd5/contrib/pantalaimon.example.conf#L1-L7

After setting the `UseKeyring` value, you'll probably have to generate a new access token and update the bot configuration accordingly. But that might resolve the issue.

**Comment by dillfrescott** [comment]
Thank you! I appreciate the help!
