### ISSUE TITLE
Request: Ability to set the temperature of the bot.

### ISSUE THREAD

**Issue by dillfrescott** [PrivateCoffee/matrix-gptbot#13]
This would be very useful as I think google flash defaults to a temperature of 1 and thats a bit high for my usecases.

**Comment by kumitterer** [comment]
Closed with 8e0cffe / v0.3.11

https://github.com/PrivateCoffee/matrix-gptbot/blob/9178ab23ac8ce90eea06fdd0597612c76f7323a9/config.dist.ini#L133-L147

**Comment by dillfrescott** [comment]
Thank you so much!!!! 💓
